# _config.yml

# required, replace with your own information -----
title: Aisling Rayne, PhD
author: Aisling Rayne
description: > 
  An introduction to me, my collaborators, and our research.
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

